
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: spin-
spec:
  serviceAccountName: default
  entrypoint: sample
  arguments:
    parameters:
    - {name: rate, value: 1000}
    - {name: duration, value: 180}
    - {name: limit_cpu, value: 100m}
    - {name: limit_memory, value: 128Mi}
  templates:
    - name: sample
      steps:

        - - name: fluentbit-only
            template: fluentbit-only

        - - name: fluentd-only
            template: fluentd-only


    - name: fluentbit-only
      resource:
        action: create
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: Workflow
          metadata:
            generateName: fluentbit-only-
          spec:
            arguments:
              parameters:
              - {name: wf-name, value: "config-parse-fluentbit-only" }
              - {name: values_path, value: "config-parse-fluentbit-only" }
              - {name: rate, value: "{{workflow.parameters.rate}}"}
              - {name: duration, value: "{{workflow.parameters.duration}}"}
              - {name: limit_cpu, value: "{{workflow.parameters.limit_cpu}}"}
              - {name: limit_memory, value: "{{workflow.parameters.limit_memory}}"}
            workflowTemplateRef:
              name: fluentbit-only
        successCondition: status.phase == Succeeded
        failureCondition: status.phase in (Failed, Error)

    - name: fluentd-only
      resource:
        action: create
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: Workflow
          metadata:
            generateName: fluentd-only-
          spec:
            arguments:
              parameters:
              - {name: wf-name, value: "config-parse-fluentd-only" }
              - {name: values_path, value: "config-parse-fluentd-only" }
              - {name: rate, value: "{{workflow.parameters.rate}}"}
              - {name: duration, value: "{{workflow.parameters.duration}}"}
              - {name: limit_cpu, value: "{{workflow.parameters.limit_cpu}}"}
              - {name: limit_memory, value: "{{workflow.parameters.limit_memory}}"}
            workflowTemplateRef:
              name: fluentd-only
        successCondition: status.phase == Succeeded
        failureCondition: status.phase in (Failed, Error)

