
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: path-
spec:
  serviceAccountName: default
  entrypoint: sample
  arguments:
    parameters:
    - {name: rate, value: 1000}
    - {name: duration, value: 180}
    - {name: limit_cpu, value: 100m}
    - {name: limit_memory, value: 128Mi}
  templates:
    - name: sample
      steps:

        - - name: paththrough-fluentbit-only
            template: paththrough-fluentbit-only

        - - name: paththrough-fluentd-only
            template: paththrough-fluentd-only

        - - name: paththrough-aggregator
            template: paththrough-aggregator


    - name: paththrough-fluentbit-only
      resource:
        action: create
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: Workflow
          metadata:
            generateName: paththrough-fluentbit-only-
          spec:
            arguments:
              parameters:
              - {name: wf-name, value: "paththrough-fluentbit-only" }
              - {name: values_path, value: "paththrough-fluentbit-only" }
              - {name: rate, value: "{{workflow.parameters.rate}}"}
              - {name: duration, value: "{{workflow.parameters.duration}}"}
              - {name: limit_cpu, value: "{{workflow.parameters.limit_cpu}}"}
              - {name: limit_memory, value: "{{workflow.parameters.limit_memory}}"}
            workflowTemplateRef:
              name: fluentbit-only
        successCondition: status.phase == Succeeded
        failureCondition: status.phase in (Failed, Error)

    - name: paththrough-fluentd-only
      resource:
        action: create
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: Workflow
          metadata:
            generateName: paththrough-fluentd-only-
          spec:
            arguments:
              parameters:
              - {name: wf-name, value: "paththrough-fluentd-only" }
              - {name: values_path, value: "paththrough-fluentd-only" }
              - {name: rate, value: "{{workflow.parameters.rate}}"}
              - {name: duration, value: "{{workflow.parameters.duration}}"}
              - {name: limit_cpu, value: "{{workflow.parameters.limit_cpu}}"}
              - {name: limit_memory, value: "{{workflow.parameters.limit_memory}}"}
            workflowTemplateRef:
              name: fluentd-only
        successCondition: status.phase == Succeeded
        failureCondition: status.phase in (Failed, Error)

    - name: paththrough-aggregator
      resource:
        action: create
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: Workflow
          metadata:
            generateName: paththrough-aggregator-
          spec:
            arguments:
              parameters:
              - {name: wf-name, value: "paththrough-aggregator" }
              - {name: values_path, value: "paththrough-aggregator" }
              - {name: rate, value: "{{workflow.parameters.rate}}"}
              - {name: duration, value: "{{workflow.parameters.duration}}"}
              - {name: limit_cpu, value: "{{workflow.parameters.limit_cpu}}"}
              - {name: limit_memory, value: "{{workflow.parameters.limit_memory}}"}
            workflowTemplateRef:
              name: aggregator
        successCondition: status.phase == Succeeded
        failureCondition: status.phase in (Failed, Error)

