apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: sample-
spec:
  serviceAccountName: default
  entrypoint: sample
  arguments:
    parameters:
    - {name: rate, value: 1}
    - {name: duration, value: 180}
    - {name: limit_cpu, value: 100m}
    - {name: limit_memory, value: 128Mi}
  templates:
    - name: sample
      steps:
        - - name: spin-fluentd
            template: spin-fluentd
        - - name: spin-fluentbit
            template: spin-fluentbit

    - name: spin-fluentd
      resource:
        action: create
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: Workflow
          metadata:
            generateName: spin-fluentd-
          spec:
            arguments:
              parameters:
              - {name: wf-name, value: "spin-fluentd" }
              - {name: values_path, value: "spin-fluentd" }
              - {name: rate, value: "{{workflow.parameters.rate}}"}
              - {name: duration, value: "{{workflow.parameters.duration}}"}
              - {name: limit_cpu, value: "{{workflow.parameters.limit_cpu}}"}
              - {name: limit_memory, value: "{{workflow.parameters.limit_memory}}"}
            workflowTemplateRef:
              name: fluentd-only
        successCondition: status.phase == Succeeded
        failureCondition: status.phase in (Failed, Error)

    - name: spin-fluentbit
      resource:
        action: create
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: Workflow
          metadata:
            generateName: spin-fluentbit-
          spec:
            arguments:
              parameters:
              - {name: wf-name, value: "spin-fluentbit" }
              - {name: values_path, value: "spin-fluentbit" }
              - {name: rate, value: "{{workflow.parameters.rate}}"}
              - {name: duration, value: "{{workflow.parameters.duration}}"}
              - {name: limit_cpu, value: "{{workflow.parameters.limit_cpu}}"}
              - {name: limit_memory, value: "{{workflow.parameters.limit_memory}}"}
            workflowTemplateRef:
              name: fluentbit-only
        successCondition: status.phase == Succeeded
        failureCondition: status.phase in (Failed, Error)
