---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: file-buffer-fluentd-only-
spec:
  serviceAccountName: default
  entrypoint: sample
  arguments:
    parameters:
    - name: wf-name
      value: file-buffer-fluentd-only
    - name: rate
      value: 1000
    - name: duration
      value: 180
    - name: limit_cpu
      value: 100m
    - name: limit_memory
      value: 128Mi
    - name: path
      value: http://dummy-nginx.veri.svc
  templates:
  - name: sample
    steps:
    - - name: file-buffer-fluentd-only
        template: file-buffer-fluentd-only
  - name: file-buffer-fluentd-only
    resource:
      action: create
      manifest: |
        apiVersion: argoproj.io/v1alpha1
        kind: Workflow
        metadata:
          generateName: file-buffer-fluentd-only-
        spec:
          arguments:
            parameters:
            - {name: wf-name, value: "{{workflow.parameters.wf-name}}" }
            - {name: values_path, value: "{{workflow.parameters.wf-name}}" }
            - {name: rate, value: "{{workflow.parameters.rate}}"}
            - {name: duration, value: "{{workflow.parameters.duration}}"}
            - {name: limit_cpu, value: "{{workflow.parameters.limit_cpu}}"}
            - {name: limit_memory, value: "{{workflow.parameters.limit_memory}}"}
            - {name: path, value: "{{workflow.parameters.path}}"}
          workflowTemplateRef:
            name: fluentd-only
      successCondition: status.phase == Succeeded
      failureCondition: status.phase in (Failed, Error)
