---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: k8s-fluentbit-only-
spec:
  serviceAccountName: default
  entrypoint: sample
  arguments:
    parameters:
    - name: wf-name
      value: k8s-fluentbit-only
    - name: rate
      value: 1000
    - name: duration
      value: 180
    - name: limit_cpu
      value: 100m
    - name: limit_memory
      value: 128Mi
  templates:
  - name: sample
    steps:
    - - name: fluentbit-only
        template: fluentbit-only
  - name: fluentbit-only
    resource:
      action: create
      manifest: |
        apiVersion: argoproj.io/v1alpha1
        kind: Workflow
        metadata:
          generateName: fluentbit-only-
        spec:
          arguments:
            parameters:
            - {name: wf-name, value: "{{workflow.parameters.wf-name}}" }
            - {name: values_path, value: "{{workflow.parameters.wf-name}}" }
            - {name: rate, value: "{{workflow.parameters.rate}}"}
            - {name: duration, value: "{{workflow.parameters.duration}}"}
            - {name: limit_cpu, value: "{{workflow.parameters.limit_cpu}}"}
            - {name: limit_memory, value: "{{workflow.parameters.limit_memory}}"}
          workflowTemplateRef:
            name: fluentbit-only
      successCondition: status.phase == Succeeded
      failureCondition: status.phase in (Failed, Error)
