apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: sample-
spec:
  serviceAccountName: default
  entrypoint: sample
  arguments:
    parameters:
    - {name: rate, value: 1}
    - {name: duration, value: 180}
    - {name: limit_cpu, value: 100m}
    - {name: limit_memory, value: 128Mi}
  templates:
    - name: sample
      steps:
        - - name: fluentbit-only
            template: test1

    - name: test1
      resource:
        action: create
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: Workflow
          metadata:
            generateName: test-1-
          spec:
            arguments:
              parameters:
              - {name: values_path, value: spin-fluentbit }
              - {name: rate, value: "{{workflow.parameters.rate}}"}
              - {name: duration, value: "{{workflow.parameters.duration}}"}
              - {name: limit_cpu, value: "{{workflow.parameters.limit_cpu}}"}
              - {name: limit_memory, value: "{{workflow.parameters.limit_memory}}"}
            workflowTemplateRef:
              name: fluentbit-only
        successCondition: status.phase == Succeeded
        failureCondition: status.phase in (Failed, Error)
