global:
  name: config
  rate: 1000
  duration: 180
  limit_cpu: 100m
  limit_memory: 128Mi

values:
  - config-parse-fluentbit-only:
      template: fluentbit-only
  - config-parse-fluentd-only:
      template: fluentd-only
