global:
  name: spin
  rate: 1000
  duration: 180
  limit_cpu: 100m
  limit_memory: 128Mi

values:
  - config-parse-fluentbit-only:
      workflow: fluentbit-only
  - config-parse-fluentd-only:
      workflow: fluentd-only
